"""initial

Revision ID: 3fe0be1aeff9
Revises: 
Create Date: 2026-05-16 13:24:13.514924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fe0be1aeff9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('user', 'admin', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('predict',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('environmental_humidity', sa.Float(), nullable=False),
    sa.Column('soil_moisture', sa.Float(), nullable=False),
    sa.Column('light', sa.Float(), nullable=False),
    sa.Column('current_time_of_the_day', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predict_user_id'), 'predict', ['user_id'], unique=False)
    op.create_table('prediction_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('predict_id', sa.UUID(), nullable=False),
    sa.Column('temperature_alert', sa.Enum('without_alert', 'mild_alert', 'alert', name='temperature_status'), nullable=False),
    sa.Column('light_temperature', sa.Enum('enough_light', 'little_light', 'insufficient_light', name='light_temperature_status'), nullable=False),
    sa.Column('ambient_humidity_alert', sa.Enum('normal', 'dry_air', 'risk_of_mold', name='ambient_status'), nullable=False),
    sa.Column('watering', sa.Enum('do_not_water', 'watering', name='watering_status'), nullable=False),
    sa.Column('crop_status', sa.Enum('optimal', 'mild_stress', 'severe_stress', name='crop_status'), nullable=False),
    sa.ForeignKeyConstraint(['predict_id'], ['predict.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prediction_results_predict_id'), 'prediction_results', ['predict_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prediction_results_predict_id'), table_name='prediction_results')
    op.drop_table('prediction_results')
    op.drop_index(op.f('ix_predict_user_id'), table_name='predict')
    op.drop_table('predict')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
